# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-29 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('0', 'NONE'), ('1', 'ICMP'), ('6', 'TCP'), ('17', 'UDP')], max_length=2)),
                ('sourceIP', models.GenericIPAddressField()),
                ('sourcePort', models.PositiveIntegerField()),
                ('desIP', models.GenericIPAddressField()),
                ('desPort', models.PositiveIntegerField()),
            ],
        ),
    ]
