# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-29 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('protocol', models.CharField(choices=[('0', 'NONE'), ('1', 'ICMP'), ('6', 'TCP'), ('17', 'UDP')], max_length=2)),
                ('sourceIP', models.GenericIPAddressField()),
                ('sourcePort', models.PositiveIntegerField()),
                ('desIP', models.GenericIPAddressField()),
                ('desPort', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='IPAddress',
            new_name='IP',
        ),
        migrations.DeleteModel(
            name='Rules',
        ),
        migrations.RenameField(
            model_name='ip',
            old_name='IP',
            new_name='IPaddress',
        ),
    ]
